-- ============================================================
--  Cloud-API-Based-Network-Application-Security
--  Database: Laptop Store — Small Company Services
--  Engine: PostgreSQL 17
-- ============================================================

-- ─────────────────────────────────────────────────────────────
--  ENUM TYPES
-- ─────────────────────────────────────────────────────────────
DROP TYPE IF EXISTS order_status CASCADE;
DROP TYPE IF EXISTS user_role    CASCADE;

CREATE TYPE order_status AS ENUM ('Pending','Processing','Shipped','Delivered','Cancelled');
CREATE TYPE user_role    AS ENUM ('customer','admin','staff');

-- ─────────────────────────────────────────────────────────────
--  DROP TABLES (đúng thứ tự phụ thuộc)
-- ─────────────────────────────────────────────────────────────
DROP TABLE IF EXISTS orders     CASCADE;
DROP TABLE IF EXISTS products   CASCADE;
DROP TABLE IF EXISTS users      CASCADE;
DROP TABLE IF EXISTS brands     CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

-- ─────────────────────────────────────────────────────────────
--  TABLE: brands
-- ─────────────────────────────────────────────────────────────
CREATE TABLE brands (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    country     VARCHAR(50),
    website     VARCHAR(100),
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ─────────────────────────────────────────────────────────────
--  TABLE: categories
-- ─────────────────────────────────────────────────────────────
CREATE TABLE categories (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ─────────────────────────────────────────────────────────────
--  TABLE: users
-- ─────────────────────────────────────────────────────────────
CREATE TABLE users (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(100) NOT NULL UNIQUE,
    phone       VARCHAR(15),
    city        VARCHAR(100),
    role        user_role    DEFAULT 'customer',
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ─────────────────────────────────────────────────────────────
--  TABLE: products
-- ─────────────────────────────────────────────────────────────
CREATE TABLE products (
    sku         VARCHAR(20)    PRIMARY KEY,
    name        VARCHAR(150)   NOT NULL,
    brand_id    INTEGER        NOT NULL REFERENCES brands(id),
    category_id INTEGER        NOT NULL REFERENCES categories(id),
    price       NUMERIC(10,2)  NOT NULL,
    specs       TEXT,
    stock       INTEGER        DEFAULT 50,
    created_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

-- ─────────────────────────────────────────────────────────────
--  TABLE: orders
-- ─────────────────────────────────────────────────────────────
CREATE TABLE orders (
    id          INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER        NOT NULL REFERENCES users(id),
    sku         VARCHAR(20)    NOT NULL REFERENCES products(sku),
    item_name   VARCHAR(150)   NOT NULL,
    qty         INTEGER        NOT NULL DEFAULT 1 CHECK (qty > 0),
    unit_price  NUMERIC(10,2)  NOT NULL,
    total_price NUMERIC(10,2)  GENERATED ALWAYS AS (qty * unit_price) STORED,
    status      order_status   DEFAULT 'Pending',
    order_date  DATE           NOT NULL,
    created_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

-- ─────────────────────────────────────────────────────────────
--  INDEXES
-- ─────────────────────────────────────────────────────────────
CREATE INDEX idx_orders_user_id  ON orders(user_id);
CREATE INDEX idx_orders_sku      ON orders(sku);
CREATE INDEX idx_orders_status   ON orders(status);
CREATE INDEX idx_orders_date     ON orders(order_date);
CREATE INDEX idx_products_brand  ON products(brand_id);
CREATE INDEX idx_products_cat    ON products(category_id);

-- ============================================================
--  SEED DATA
-- ============================================================

-- ─────────────────────────────────────────────────────────────
--  brands
-- ─────────────────────────────────────────────────────────────
INSERT INTO brands (id, name, country, website) VALUES
(1, 'Dell',   'USA',    'https://www.dell.com'),
(2, 'Apple',  'USA',    'https://www.apple.com'),
(3, 'Lenovo', 'China',  'https://www.lenovo.com'),
(4, 'HP',     'USA',    'https://www.hp.com'),
(5, 'ASUS',   'Taiwan', 'https://www.asus.com'),
(6, 'MSI',    'Taiwan', 'https://www.msi.com');

SELECT setval(pg_get_serial_sequence('brands','id'), 6);

-- ─────────────────────────────────────────────────────────────
--  categories
-- ─────────────────────────────────────────────────────────────
INSERT INTO categories (id, name, description) VALUES
(1, 'Budget',      'Affordable laptops for everyday use'),
(2, 'Business',    'Professional laptops for office work'),
(3, 'Enterprise',  'High-security business laptops for corporations'),
(4, 'Premium',     'High-end thin & light laptops'),
(5, 'Gaming',      'High-performance gaming laptops'),
(6, 'Convertible', '2-in-1 touchscreen laptops'),
(7, 'Pro',         'Apple professional lineup');

SELECT setval(pg_get_serial_sequence('categories','id'), 7);

-- ─────────────────────────────────────────────────────────────
--  users  (20 khách hàng — id: 1..20)
-- ─────────────────────────────────────────────────────────────
INSERT INTO users (id, full_name, email, phone, city, role) VALUES
( 1, 'Nguyễn Văn An',    'an.nguyen@email.com',    '0901234567', 'Hà Nội',                  'customer'),
( 2, 'Trần Thị Bích',    'bich.tran@email.com',    '0912345678', 'Thành phố Hồ Chí Minh',  'customer'),
( 3, 'Lê Minh Cường',    'cuong.le@email.com',     '0923456789', 'Đà Nẵng',                 'customer'),
( 4, 'Phạm Thị Dung',    'dung.pham@email.com',    '0934567890', 'Cần Thơ',                 'customer'),
( 5, 'Hoàng Văn Em',     'em.hoang@email.com',     '0945678901', 'Hải Phòng',               'customer'),
( 6, 'Vũ Thị Phương',    'phuong.vu@email.com',    '0956789012', 'Huế',                     'customer'),
( 7, 'Đỗ Văn Giang',     'giang.do@email.com',     '0967890123', 'Khánh Hòa',               'customer'),
( 8, 'Bùi Thị Hoa',      'hoa.bui@email.com',      '0978901234', 'Đồng Nai',                'customer'),
( 9, 'Ngô Văn Inh',      'inh.ngo@email.com',      '0989012345', 'Gia Lai',                 'customer'),
(10, 'Đinh Thị Jên',     'jen.dinh@email.com',     '0990123456', 'Đắk Lắk',                 'customer'),
(11, 'Lý Văn Khoa',      'khoa.ly@email.com',      '0901357902', 'Lâm Đồng',                'customer'),
(12, 'Mai Thị Lan',      'lan.mai@email.com',      '0912468013', 'Quảng Ninh',              'customer'),
(13, 'Trương Văn Minh',  'minh.truong@email.com',  '0923579124', 'Nghệ An',                 'customer'),
(14, 'Cao Thị Ngọc',     'ngoc.cao@email.com',     '0934680235', 'Thanh Hóa',               'customer'),
(15, 'Dương Văn Oanh',   'oanh.duong@email.com',   '0945791346', 'Lào Cai',                 'customer'),
(16, 'Phan Thị Phúc',    'phuc.phan@email.com',    '0956802457', 'Bắc Ninh',                'customer'),
(17, 'Tạ Văn Quân',      'quan.ta@email.com',      '0967913568', 'An Giang',                'customer'),
(18, 'Lưu Thị Rương',    'ruong.luu@email.com',    '0978024679', 'Cà Mau',                  'customer'),
(19, 'Hà Văn Sơn',       'son.ha@email.com',       '0989135780', 'Vĩnh Long',               'customer'),
(20, 'Kiều Thị Tuyết',   'tuyet.kieu@email.com',   '0990246891', 'Tây Ninh',                'customer');

SELECT setval(pg_get_serial_sequence('users','id'), 20);

-- ─────────────────────────────────────────────────────────────
--  products  (55 SKU)
--  brand_id:    1=Dell 2=Apple 3=Lenovo 4=HP 5=ASUS 6=MSI
--  category_id: 1=Budget 2=Business 3=Enterprise 4=Premium 5=Gaming 6=Convertible 7=Pro
-- ─────────────────────────────────────────────────────────────
INSERT INTO products (sku, name, brand_id, category_id, price, specs) VALUES
-- Dell
('DELL-001', 'Dell Inspiron 15 3511',     1, 1,  699.00, 'Intel i5-1135G7, 8GB RAM, 512GB SSD'),
('DELL-002', 'Dell Inspiron 15 3530',     1, 1,  749.00, 'Intel i5-1334U, 16GB RAM, 512GB SSD'),
('DELL-003', 'Dell Vostro 3520',          1, 2,  820.00, 'Intel i5-1235U, 8GB RAM, 256GB SSD'),
('DELL-004', 'Dell Vostro 5620',          1, 2, 1050.00, 'Intel i7-1260P, 16GB RAM, 512GB SSD'),
('DELL-005', 'Dell Latitude 5430',        1, 3, 1300.00, 'Intel i7-1265U, 16GB RAM, 512GB SSD'),
('DELL-006', 'Dell Latitude 7430',        1, 3, 1800.00, 'Intel i7-1265U, 32GB RAM, 1TB SSD'),
('DELL-007', 'Dell XPS 13 9315',          1, 4, 1499.00, 'Intel i7-1250U, 16GB RAM, 512GB SSD'),
('DELL-008', 'Dell XPS 13 Plus 9320',     1, 4, 1799.00, 'Intel i7-1260P, 32GB RAM, 1TB SSD'),
('DELL-009', 'Dell XPS 15 9520',          1, 4, 2199.00, 'Intel i7-12700H, 32GB RAM, 1TB SSD, RTX 3050'),
('DELL-010', 'Dell G15 Gaming 5530',      1, 5, 1099.00, 'Intel i7-13650HX, 16GB RAM, 512GB SSD, RTX 3050'),
('DELL-011', 'Dell G16 Gaming 7630',      1, 5, 1499.00, 'Intel i7-13700HX, 32GB RAM, 1TB SSD, RTX 4060'),
('DELL-012', 'Dell Alienware m15 R7',     1, 5, 2499.00, 'AMD Ryzen 9 6900HX, 32GB RAM, 1TB SSD, RTX 3070Ti'),
-- Apple
('APPL-001', 'MacBook Air M1 13"',        2, 4,  999.00, 'Apple M1, 8GB RAM, 256GB SSD'),
('APPL-002', 'MacBook Air M2 13"',        2, 4, 1099.00, 'Apple M2, 8GB RAM, 256GB SSD'),
('APPL-003', 'MacBook Air M2 15"',        2, 4, 1299.00, 'Apple M2, 8GB RAM, 256GB SSD'),
('APPL-004', 'MacBook Air M3 13"',        2, 4, 1199.00, 'Apple M3, 8GB RAM, 256GB SSD'),
('APPL-005', 'MacBook Pro M2 13"',        2, 7, 1299.00, 'Apple M2, 8GB RAM, 256GB SSD'),
('APPL-006', 'MacBook Pro M3 14"',        2, 7, 1999.00, 'Apple M3 Pro, 18GB RAM, 512GB SSD'),
('APPL-007', 'MacBook Pro M3 16"',        2, 7, 2499.00, 'Apple M3 Pro, 18GB RAM, 512GB SSD'),
('APPL-008', 'MacBook Pro M3 Max 16"',    2, 7, 3499.00, 'Apple M3 Max, 36GB RAM, 1TB SSD'),
-- Lenovo
('LNVO-001', 'Lenovo IdeaPad 3 15',       3, 1,  549.00, 'AMD Ryzen 5 7520U, 8GB RAM, 256GB SSD'),
('LNVO-002', 'Lenovo IdeaPad Slim 5',     3, 1,  699.00, 'AMD Ryzen 5 7530U, 16GB RAM, 512GB SSD'),
('LNVO-003', 'Lenovo IdeaPad Flex 5',     3, 6,  849.00, 'AMD Ryzen 5 7530U, 16GB RAM, 512GB SSD'),
('LNVO-004', 'Lenovo ThinkPad E15 G4',    3, 2,  899.00, 'Intel i5-1235U, 16GB RAM, 512GB SSD'),
('LNVO-005', 'Lenovo ThinkPad T14s G3',   3, 3, 1250.00, 'AMD Ryzen 7 Pro 6850U, 16GB RAM, 512GB SSD'),
('LNVO-006', 'Lenovo ThinkPad X1 Carbon', 3, 3, 1799.00, 'Intel i7-1265U, 16GB RAM, 512GB SSD'),
('LNVO-007', 'Lenovo Legion 5 Gen 8',     3, 5, 1099.00, 'AMD Ryzen 7 7745HX, 16GB RAM, 512GB SSD, RTX 4060'),
('LNVO-008', 'Lenovo Legion 5 Pro G8',    3, 5, 1399.00, 'AMD Ryzen 9 7945HX, 32GB RAM, 1TB SSD, RTX 4070'),
('LNVO-009', 'Lenovo Legion 7 Gen 8',     3, 5, 1999.00, 'AMD Ryzen 9 7945HX, 32GB RAM, 1TB SSD, RTX 4080'),
('LNVO-010', 'Lenovo Yoga 7 Gen 8',       3, 6,  999.00, 'AMD Ryzen 7 7730U, 16GB RAM, 512GB SSD'),
-- HP
('HP-001',   'HP 15s-fq5110TU',           4, 1,  599.00, 'Intel i5-1235U, 8GB RAM, 512GB SSD'),
('HP-002',   'HP Pavilion 15-eg3086TU',   4, 1,  749.00, 'Intel i5-1335U, 16GB RAM, 512GB SSD'),
('HP-003',   'HP Pavilion x360 14"',      4, 6,  849.00, 'Intel i5-1335U, 16GB RAM, 512GB SSD'),
('HP-004',   'HP ProBook 440 G10',        4, 2,  950.00, 'Intel i5-1335U, 16GB RAM, 512GB SSD'),
('HP-005',   'HP EliteBook 840 G10',      4, 3, 1499.00, 'Intel i7-1355U, 16GB RAM, 512GB SSD'),
('HP-006',   'HP Spectre x360 14"',       4, 4, 1699.00, 'Intel i7-1355U, 16GB RAM, 1TB SSD'),
('HP-007',   'HP Spectre x360 16"',       4, 4, 1999.00, 'Intel i7-13700H, 32GB RAM, 1TB SSD'),
('HP-008',   'HP Omen 16 Gaming',         4, 5, 1299.00, 'Intel i7-13700HX, 16GB RAM, 512GB SSD, RTX 4060'),
('HP-009',   'HP Omen 17 Gaming',         4, 5, 1799.00, 'Intel i9-13900HX, 32GB RAM, 1TB SSD, RTX 4070'),
-- ASUS
('ASUS-001', 'ASUS VivoBook 15 X515',     5, 1,  549.00, 'Intel i5-1135G7, 8GB RAM, 512GB SSD'),
('ASUS-002', 'ASUS VivoBook 15X OLED',    5, 1,  699.00, 'AMD Ryzen 5 5600H, 16GB RAM, 512GB SSD'),
('ASUS-003', 'ASUS ZenBook 14 OLED',      5, 4,  999.00, 'AMD Ryzen 7 7730U, 16GB RAM, 512GB SSD'),
('ASUS-004', 'ASUS ZenBook 14X OLED',     5, 4, 1199.00, 'Intel i7-12700H, 16GB RAM, 512GB SSD'),
('ASUS-005', 'ASUS ExpertBook B1 B1502',  5, 2,  799.00, 'Intel i5-1235U, 8GB RAM, 512GB SSD'),
('ASUS-006', 'ASUS ExpertBook B9 B9403',  5, 3, 1699.00, 'Intel i7-1355U, 16GB RAM, 1TB SSD'),
('ASUS-007', 'ASUS ROG Strix G15',        5, 5, 1299.00, 'AMD Ryzen 9 7945HX, 16GB RAM, 512GB SSD, RTX 4070'),
('ASUS-008', 'ASUS ROG Zephyrus G14',     5, 5, 1499.00, 'AMD Ryzen 9 7940HS, 16GB RAM, 1TB SSD, RTX 4060'),
('ASUS-009', 'ASUS ROG Zephyrus G16',     5, 5, 1999.00, 'Intel i9-13900H, 32GB RAM, 1TB SSD, RTX 4080'),
('ASUS-010', 'ASUS TUF Gaming A15',       5, 5,  899.00, 'AMD Ryzen 7 7745HX, 16GB RAM, 512GB SSD, RTX 4060'),
-- MSI
('MSI-001',  'MSI Modern 14 C12M',        6, 2,  699.00, 'Intel i5-1235U, 8GB RAM, 512GB SSD'),
('MSI-002',  'MSI Prestige 14 Evo',       6, 2,  999.00, 'Intel i7-1280P, 16GB RAM, 1TB SSD'),
('MSI-003',  'MSI Stealth 15M',           6, 5,  999.00, 'Intel i7-12650H, 16GB RAM, 512GB SSD, RTX 3060'),
('MSI-004',  'MSI Raider GE68HX',         6, 5, 2499.00, 'Intel i9-13950HX, 32GB RAM, 2TB SSD, RTX 4080'),
('MSI-005',  'MSI Katana 15 B12V',        6, 5,  999.00, 'Intel i7-12650H, 16GB RAM, 512GB SSD, RTX 4060'),
('MSI-006',  'MSI Titan GT77',            6, 5, 3499.00, 'Intel i9-13980HX, 64GB RAM, 4TB SSD, RTX 4090');

-- ─────────────────────────────────────────────────────────────
--  orders  (200 đơn hàng — user_id INTEGER 1..20)
-- ─────────────────────────────────────────────────────────────
INSERT INTO orders (id, user_id, sku, item_name, qty, unit_price, status, order_date) VALUES
-- user 1 · Nguyễn Văn An · Hà Nội
(101,  1, 'DELL-001', 'Dell Inspiron 15 3511',      1,  699.00, 'Shipped',    '2024-03-12'),
(102,  1, 'LNVO-001', 'Lenovo IdeaPad 3 15',        1,  549.00, 'Delivered',  '2024-05-20'),
(103,  1, 'HP-001',   'HP 15s-fq5110TU',            2,  599.00, 'Delivered',  '2024-07-08'),
(104,  1, 'ASUS-001', 'ASUS VivoBook 15 X515',      1,  549.00, 'Pending',    '2024-09-15'),
(105,  1, 'DELL-003', 'Dell Vostro 3520',           1,  820.00, 'Processing', '2024-11-02'),
(106,  1, 'APPL-001', 'MacBook Air M1 13"',         1,  999.00, 'Delivered',  '2025-01-10'),
(107,  1, 'LNVO-004', 'Lenovo ThinkPad E15 G4',     1,  899.00, 'Shipped',    '2025-02-14'),
(108,  1, 'MSI-001',  'MSI Modern 14 C12M',         1,  699.00, 'Cancelled',  '2024-04-22'),
(109,  1, 'HP-004',   'HP ProBook 440 G10',         1,  950.00, 'Delivered',  '2024-06-30'),
(110,  1, 'DELL-007', 'Dell XPS 13 9315',           1, 1499.00, 'Processing', '2024-12-05'),
-- user 2 · Trần Thị Bích · Thành phố Hồ Chí Minh
(111,  2, 'APPL-002', 'MacBook Air M2 13"',         1, 1099.00, 'Delivered',  '2024-02-18'),
(112,  2, 'APPL-006', 'MacBook Pro M3 14"',         1, 1999.00, 'Shipped',    '2024-04-10'),
(113,  2, 'DELL-009', 'Dell XPS 15 9520',           1, 2199.00, 'Delivered',  '2024-06-25'),
(114,  2, 'LNVO-006', 'Lenovo ThinkPad X1 Carbon',  1, 1799.00, 'Processing', '2024-08-14'),
(115,  2, 'HP-006',   'HP Spectre x360 14"',        1, 1699.00, 'Delivered',  '2024-10-03'),
(116,  2, 'ASUS-004', 'ASUS ZenBook 14X OLED',      1, 1199.00, 'Shipped',    '2024-11-28'),
(117,  2, 'MSI-002',  'MSI Prestige 14 Evo',        1,  999.00, 'Pending',    '2025-01-05'),
(118,  2, 'DELL-008', 'Dell XPS 13 Plus 9320',      1, 1799.00, 'Delivered',  '2024-03-30'),
(119,  2, 'APPL-004', 'MacBook Air M3 13"',         2, 1199.00, 'Delivered',  '2024-07-19'),
(120,  2, 'LNVO-009', 'Lenovo Legion 7 Gen 8',      1, 1999.00, 'Cancelled',  '2024-09-07'),
-- user 3 · Lê Minh Cường · Đà Nẵng
(121,  3, 'DELL-010', 'Dell G15 Gaming 5530',       1, 1099.00, 'Delivered',  '2024-01-25'),
(122,  3, 'ASUS-007', 'ASUS ROG Strix G15',         1, 1299.00, 'Shipped',    '2024-03-17'),
(123,  3, 'LNVO-007', 'Lenovo Legion 5 Gen 8',      1, 1099.00, 'Delivered',  '2024-05-06'),
(124,  3, 'HP-008',   'HP Omen 16 Gaming',          1, 1299.00, 'Processing', '2024-07-22'),
(125,  3, 'MSI-003',  'MSI Stealth 15M',            1,  999.00, 'Delivered',  '2024-09-11'),
(126,  3, 'DELL-011', 'Dell G16 Gaming 7630',       1, 1499.00, 'Pending',    '2024-11-18'),
(127,  3, 'ASUS-010', 'ASUS TUF Gaming A15',        2,  899.00, 'Delivered',  '2025-01-08'),
(128,  3, 'LNVO-008', 'Lenovo Legion 5 Pro G8',     1, 1399.00, 'Shipped',    '2024-04-05'),
(129,  3, 'MSI-005',  'MSI Katana 15 B12V',         1,  999.00, 'Cancelled',  '2024-08-30'),
(130,  3, 'HP-009',   'HP Omen 17 Gaming',          1, 1799.00, 'Delivered',  '2024-12-20'),
-- user 4 · Phạm Thị Dung · Cần Thơ
(131,  4, 'DELL-005', 'Dell Latitude 5430',         1, 1300.00, 'Delivered',  '2024-02-09'),
(132,  4, 'HP-005',   'HP EliteBook 840 G10',       1, 1499.00, 'Shipped',    '2024-04-28'),
(133,  4, 'LNVO-005', 'Lenovo ThinkPad T14s G3',    1, 1250.00, 'Delivered',  '2024-06-14'),
(134,  4, 'DELL-006', 'Dell Latitude 7430',         1, 1800.00, 'Processing', '2024-08-03'),
(135,  4, 'ASUS-006', 'ASUS ExpertBook B9 B9403',   1, 1699.00, 'Delivered',  '2024-10-22'),
(136,  4, 'HP-007',   'HP Spectre x360 16"',        1, 1999.00, 'Pending',    '2024-12-11'),
(137,  4, 'LNVO-006', 'Lenovo ThinkPad X1 Carbon',  2, 1799.00, 'Shipped',    '2025-02-01'),
(138,  4, 'DELL-007', 'Dell XPS 13 9315',           1, 1499.00, 'Delivered',  '2024-03-21'),
(139,  4, 'MSI-002',  'MSI Prestige 14 Evo',        1,  999.00, 'Delivered',  '2024-07-10'),
(140,  4, 'ASUS-005', 'ASUS ExpertBook B1 B1502',   1,  799.00, 'Cancelled',  '2024-09-25'),
-- user 5 · Hoàng Văn Em · Hải Phòng
(141,  5, 'LNVO-003', 'Lenovo IdeaPad Flex 5',      1,  849.00, 'Delivered',  '2024-01-30'),
(142,  5, 'HP-003',   'HP Pavilion x360 14"',       1,  849.00, 'Shipped',    '2024-04-15'),
(143,  5, 'ASUS-003', 'ASUS ZenBook 14 OLED',       1,  999.00, 'Delivered',  '2024-06-08'),
(144,  5, 'DELL-002', 'Dell Inspiron 15 3530',      1,  749.00, 'Processing', '2024-08-27'),
(145,  5, 'LNVO-010', 'Lenovo Yoga 7 Gen 8',        1,  999.00, 'Delivered',  '2024-10-16'),
(146,  5, 'HP-002',   'HP Pavilion 15-eg3086TU',    2,  749.00, 'Pending',    '2024-12-04'),
(147,  5, 'ASUS-002', 'ASUS VivoBook 15X OLED',     1,  699.00, 'Delivered',  '2025-01-22'),
(148,  5, 'LNVO-002', 'Lenovo IdeaPad Slim 5',      1,  699.00, 'Shipped',    '2024-03-08'),
(149,  5, 'DELL-001', 'Dell Inspiron 15 3511',      1,  699.00, 'Delivered',  '2024-07-31'),
(150,  5, 'HP-001',   'HP 15s-fq5110TU',            1,  599.00, 'Cancelled',  '2024-09-19'),
-- user 6 · Vũ Thị Phương · Huế
(151,  6, 'APPL-005', 'MacBook Pro M2 13"',         1, 1299.00, 'Delivered',  '2024-02-26'),
(152,  6, 'APPL-007', 'MacBook Pro M3 16"',         1, 2499.00, 'Shipped',    '2024-05-13'),
(153,  6, 'APPL-008', 'MacBook Pro M3 Max 16"',     1, 3499.00, 'Delivered',  '2024-07-02'),
(154,  6, 'APPL-003', 'MacBook Air M2 15"',         1, 1299.00, 'Processing', '2024-09-21'),
(155,  6, 'APPL-001', 'MacBook Air M1 13"',         2,  999.00, 'Delivered',  '2024-11-10'),
(156,  6, 'DELL-008', 'Dell XPS 13 Plus 9320',      1, 1799.00, 'Pending',    '2025-01-28'),
(157,  6, 'HP-006',   'HP Spectre x360 14"',        1, 1699.00, 'Delivered',  '2024-04-18'),
(158,  6, 'ASUS-004', 'ASUS ZenBook 14X OLED',      1, 1199.00, 'Shipped',    '2024-08-07'),
(159,  6, 'LNVO-010', 'Lenovo Yoga 7 Gen 8',        1,  999.00, 'Delivered',  '2024-12-25'),
(160,  6, 'MSI-002',  'MSI Prestige 14 Evo',        1,  999.00, 'Cancelled',  '2024-06-20'),
-- user 7 · Đỗ Văn Giang · Khánh Hòa
(161,  7, 'DELL-012', 'Dell Alienware m15 R7',      1, 2499.00, 'Delivered',  '2024-01-14'),
(162,  7, 'ASUS-009', 'ASUS ROG Zephyrus G16',      1, 1999.00, 'Shipped',    '2024-03-03'),
(163,  7, 'MSI-004',  'MSI Raider GE68HX',          1, 2499.00, 'Delivered',  '2024-05-22'),
(164,  7, 'LNVO-009', 'Lenovo Legion 7 Gen 8',      1, 1999.00, 'Processing', '2024-07-11'),
(165,  7, 'HP-009',   'HP Omen 17 Gaming',          1, 1799.00, 'Delivered',  '2024-09-29'),
(166,  7, 'ASUS-008', 'ASUS ROG Zephyrus G14',      1, 1499.00, 'Pending',    '2024-11-17'),
(167,  7, 'MSI-006',  'MSI Titan GT77',             1, 3499.00, 'Delivered',  '2025-01-06'),
(168,  7, 'DELL-011', 'Dell G16 Gaming 7630',       2, 1499.00, 'Shipped',    '2024-04-12'),
(169,  7, 'LNVO-008', 'Lenovo Legion 5 Pro G8',     1, 1399.00, 'Delivered',  '2024-08-01'),
(170,  7, 'HP-008',   'HP Omen 16 Gaming',          1, 1299.00, 'Cancelled',  '2024-10-20'),
-- user 8 · Bùi Thị Hoa · Đồng Nai
(171,  8, 'DELL-003', 'Dell Vostro 3520',           1,  820.00, 'Delivered',  '2024-02-05'),
(172,  8, 'HP-004',   'HP ProBook 440 G10',         1,  950.00, 'Shipped',    '2024-04-24'),
(173,  8, 'LNVO-004', 'Lenovo ThinkPad E15 G4',     1,  899.00, 'Delivered',  '2024-06-13'),
(174,  8, 'ASUS-005', 'ASUS ExpertBook B1 B1502',   2,  799.00, 'Processing', '2024-08-02'),
(175,  8, 'DELL-004', 'Dell Vostro 5620',           1, 1050.00, 'Delivered',  '2024-09-21'),
(176,  8, 'MSI-001',  'MSI Modern 14 C12M',         1,  699.00, 'Pending',    '2024-11-09'),
(177,  8, 'HP-002',   'HP Pavilion 15-eg3086TU',    1,  749.00, 'Delivered',  '2025-01-27'),
(178,  8, 'LNVO-001', 'Lenovo IdeaPad 3 15',        1,  549.00, 'Shipped',    '2024-03-16'),
(179,  8, 'DELL-002', 'Dell Inspiron 15 3530',      1,  749.00, 'Delivered',  '2024-07-05'),
(180,  8, 'ASUS-001', 'ASUS VivoBook 15 X515',      1,  549.00, 'Cancelled',  '2024-10-13'),
-- user 9 · Ngô Văn Inh · Gia Lai
(181,  9, 'APPL-002', 'MacBook Air M2 13"',         1, 1099.00, 'Delivered',  '2024-01-08'),
(182,  9, 'DELL-007', 'Dell XPS 13 9315',           1, 1499.00, 'Shipped',    '2024-03-27'),
(183,  9, 'HP-006',   'HP Spectre x360 14"',        1, 1699.00, 'Delivered',  '2024-05-16'),
(184,  9, 'LNVO-006', 'Lenovo ThinkPad X1 Carbon',  1, 1799.00, 'Processing', '2024-07-04'),
(185,  9, 'ASUS-003', 'ASUS ZenBook 14 OLED',       1,  999.00, 'Delivered',  '2024-08-23'),
(186,  9, 'DELL-009', 'Dell XPS 15 9520',           1, 2199.00, 'Pending',    '2024-10-11'),
(187,  9, 'APPL-006', 'MacBook Pro M3 14"',         1, 1999.00, 'Delivered',  '2024-12-30'),
(188,  9, 'MSI-002',  'MSI Prestige 14 Evo',        1,  999.00, 'Shipped',    '2024-04-08'),
(189,  9, 'HP-007',   'HP Spectre x360 16"',        1, 1999.00, 'Delivered',  '2024-08-18'),
(190,  9, 'LNVO-010', 'Lenovo Yoga 7 Gen 8',        1,  999.00, 'Cancelled',  '2024-11-06'),
-- user 10 · Đinh Thị Jên · Đắk Lắk
(191, 10, 'DELL-010', 'Dell G15 Gaming 5530',       1, 1099.00, 'Delivered',  '2024-02-12'),
(192, 10, 'LNVO-007', 'Lenovo Legion 5 Gen 8',      1, 1099.00, 'Shipped',    '2024-04-01'),
(193, 10, 'ASUS-007', 'ASUS ROG Strix G15',         1, 1299.00, 'Delivered',  '2024-05-20'),
(194, 10, 'HP-008',   'HP Omen 16 Gaming',          2, 1299.00, 'Processing', '2024-07-09'),
(195, 10, 'MSI-005',  'MSI Katana 15 B12V',         1,  999.00, 'Delivered',  '2024-08-28'),
(196, 10, 'DELL-011', 'Dell G16 Gaming 7630',       1, 1499.00, 'Pending',    '2024-10-17'),
(197, 10, 'ASUS-010', 'ASUS TUF Gaming A15',        1,  899.00, 'Delivered',  '2024-12-06'),
(198, 10, 'LNVO-008', 'Lenovo Legion 5 Pro G8',     1, 1399.00, 'Shipped',    '2025-01-24'),
(199, 10, 'MSI-003',  'MSI Stealth 15M',            1,  999.00, 'Delivered',  '2024-03-13'),
(200, 10, 'HP-009',   'HP Omen 17 Gaming',          1, 1799.00, 'Cancelled',  '2024-09-02'),
-- user 11 · Lý Văn Khoa · Lâm Đồng
(201, 11, 'DELL-005', 'Dell Latitude 5430',         1, 1300.00, 'Delivered',  '2024-01-19'),
(202, 11, 'LNVO-005', 'Lenovo ThinkPad T14s G3',    1, 1250.00, 'Shipped',    '2024-03-08'),
(203, 11, 'HP-005',   'HP EliteBook 840 G10',       1, 1499.00, 'Delivered',  '2024-04-27'),
(204, 11, 'ASUS-006', 'ASUS ExpertBook B9 B9403',   1, 1699.00, 'Processing', '2024-06-15'),
(205, 11, 'DELL-006', 'Dell Latitude 7430',         1, 1800.00, 'Delivered',  '2024-08-04'),
(206, 11, 'MSI-001',  'MSI Modern 14 C12M',         2,  699.00, 'Pending',    '2024-09-23'),
(207, 11, 'LNVO-004', 'Lenovo ThinkPad E15 G4',     1,  899.00, 'Delivered',  '2024-11-11'),
(208, 11, 'HP-004',   'HP ProBook 440 G10',         1,  950.00, 'Shipped',    '2025-01-29'),
(209, 11, 'DELL-003', 'Dell Vostro 3520',           1,  820.00, 'Delivered',  '2024-03-24'),
(210, 11, 'ASUS-005', 'ASUS ExpertBook B1 B1502',   1,  799.00, 'Cancelled',  '2024-07-13'),
-- user 12 · Mai Thị Lan · Quảng Ninh
(211, 12, 'APPL-003', 'MacBook Air M2 15"',         1, 1299.00, 'Delivered',  '2024-02-17'),
(212, 12, 'APPL-007', 'MacBook Pro M3 16"',         1, 2499.00, 'Shipped',    '2024-04-06'),
(213, 12, 'DELL-008', 'Dell XPS 13 Plus 9320',      1, 1799.00, 'Delivered',  '2024-05-25'),
(214, 12, 'HP-007',   'HP Spectre x360 16"',        1, 1999.00, 'Processing', '2024-07-14'),
(215, 12, 'ASUS-004', 'ASUS ZenBook 14X OLED',      1, 1199.00, 'Delivered',  '2024-09-02'),
(216, 12, 'LNVO-010', 'Lenovo Yoga 7 Gen 8',        1,  999.00, 'Pending',    '2024-10-21'),
(217, 12, 'APPL-004', 'MacBook Air M3 13"',         1, 1199.00, 'Delivered',  '2024-12-09'),
(218, 12, 'DELL-007', 'Dell XPS 13 9315',           1, 1499.00, 'Shipped',    '2025-01-27'),
(219, 12, 'HP-006',   'HP Spectre x360 14"',        2, 1699.00, 'Delivered',  '2024-04-14'),
(220, 12, 'MSI-002',  'MSI Prestige 14 Evo',        1,  999.00, 'Cancelled',  '2024-08-04'),
-- user 13 · Trương Văn Minh · Nghệ An
(221, 13, 'DELL-010', 'Dell G15 Gaming 5530',       1, 1099.00, 'Delivered',  '2024-01-23'),
(222, 13, 'ASUS-008', 'ASUS ROG Zephyrus G14',      1, 1499.00, 'Shipped',    '2024-03-12'),
(223, 13, 'LNVO-007', 'Lenovo Legion 5 Gen 8',      2, 1099.00, 'Delivered',  '2024-05-01'),
(224, 13, 'MSI-004',  'MSI Raider GE68HX',          1, 2499.00, 'Processing', '2024-06-19'),
(225, 13, 'HP-008',   'HP Omen 16 Gaming',          1, 1299.00, 'Delivered',  '2024-08-08'),
(226, 13, 'DELL-012', 'Dell Alienware m15 R7',      1, 2499.00, 'Pending',    '2024-09-27'),
(227, 13, 'ASUS-009', 'ASUS ROG Zephyrus G16',      1, 1999.00, 'Delivered',  '2024-11-15'),
(228, 13, 'LNVO-009', 'Lenovo Legion 7 Gen 8',      1, 1999.00, 'Shipped',    '2025-01-03'),
(229, 13, 'MSI-006',  'MSI Titan GT77',             1, 3499.00, 'Delivered',  '2024-04-20'),
(230, 13, 'HP-009',   'HP Omen 17 Gaming',          1, 1799.00, 'Cancelled',  '2024-07-29'),
-- user 14 · Cao Thị Ngọc · Thanh Hóa
(231, 14, 'APPL-001', 'MacBook Air M1 13"',         1,  999.00, 'Delivered',  '2024-02-03'),
(232, 14, 'APPL-006', 'MacBook Pro M3 14"',         1, 1999.00, 'Shipped',    '2024-04-22'),
(233, 14, 'DELL-009', 'Dell XPS 15 9520',           1, 2199.00, 'Delivered',  '2024-06-11'),
(234, 14, 'LNVO-006', 'Lenovo ThinkPad X1 Carbon',  1, 1799.00, 'Processing', '2024-07-30'),
(235, 14, 'HP-007',   'HP Spectre x360 16"',        1, 1999.00, 'Delivered',  '2024-09-18'),
(236, 14, 'ASUS-003', 'ASUS ZenBook 14 OLED',       2,  999.00, 'Pending',    '2024-11-06'),
(237, 14, 'APPL-008', 'MacBook Pro M3 Max 16"',     1, 3499.00, 'Delivered',  '2024-12-25'),
(238, 14, 'DELL-008', 'Dell XPS 13 Plus 9320',      1, 1799.00, 'Shipped',    '2025-02-12'),
(239, 14, 'MSI-002',  'MSI Prestige 14 Evo',        1,  999.00, 'Delivered',  '2024-05-17'),
(240, 14, 'HP-005',   'HP EliteBook 840 G10',       1, 1499.00, 'Cancelled',  '2024-08-26'),
-- user 15 · Dương Văn Oanh · Lào Cai
(241, 15, 'DELL-001', 'Dell Inspiron 15 3511',      2,  699.00, 'Delivered',  '2024-01-11'),
(242, 15, 'HP-001',   'HP 15s-fq5110TU',            1,  599.00, 'Shipped',    '2024-03-01'),
(243, 15, 'LNVO-002', 'Lenovo IdeaPad Slim 5',      1,  699.00, 'Delivered',  '2024-04-19'),
(244, 15, 'ASUS-002', 'ASUS VivoBook 15X OLED',     1,  699.00, 'Processing', '2024-06-07'),
(245, 15, 'DELL-002', 'Dell Inspiron 15 3530',      1,  749.00, 'Delivered',  '2024-07-26'),
(246, 15, 'HP-002',   'HP Pavilion 15-eg3086TU',    1,  749.00, 'Pending',    '2024-09-14'),
(247, 15, 'LNVO-001', 'Lenovo IdeaPad 3 15',        2,  549.00, 'Delivered',  '2024-11-02'),
(248, 15, 'ASUS-001', 'ASUS VivoBook 15 X515',      1,  549.00, 'Shipped',    '2024-12-20'),
(249, 15, 'MSI-001',  'MSI Modern 14 C12M',         1,  699.00, 'Delivered',  '2025-02-07'),
(250, 15, 'DELL-003', 'Dell Vostro 3520',           1,  820.00, 'Cancelled',  '2024-04-30'),
-- user 16 · Phan Thị Phúc · Bắc Ninh
(251, 16, 'DELL-005', 'Dell Latitude 5430',         1, 1300.00, 'Delivered',  '2024-01-28'),
(252, 16, 'LNVO-005', 'Lenovo ThinkPad T14s G3',    1, 1250.00, 'Shipped',    '2024-03-18'),
(253, 16, 'HP-005',   'HP EliteBook 840 G10',       1, 1499.00, 'Delivered',  '2024-05-07'),
(254, 16, 'ASUS-006', 'ASUS ExpertBook B9 B9403',   1, 1699.00, 'Processing', '2024-06-25'),
(255, 16, 'DELL-004', 'Dell Vostro 5620',           2, 1050.00, 'Delivered',  '2024-08-13'),
(256, 16, 'MSI-001',  'MSI Modern 14 C12M',         1,  699.00, 'Pending',    '2024-10-01'),
(257, 16, 'LNVO-004', 'Lenovo ThinkPad E15 G4',     1,  899.00, 'Delivered',  '2024-11-20'),
(258, 16, 'HP-004',   'HP ProBook 440 G10',         1,  950.00, 'Shipped',    '2025-01-08'),
(259, 16, 'DELL-006', 'Dell Latitude 7430',         1, 1800.00, 'Delivered',  '2024-03-26'),
(260, 16, 'ASUS-005', 'ASUS ExpertBook B1 B1502',   1,  799.00, 'Cancelled',  '2024-09-15'),
-- user 17 · Tạ Văn Quân · An Giang
(261, 17, 'APPL-002', 'MacBook Air M2 13"',         1, 1099.00, 'Delivered',  '2024-02-14'),
(262, 17, 'HP-006',   'HP Spectre x360 14"',        1, 1699.00, 'Shipped',    '2024-04-03'),
(263, 17, 'DELL-007', 'Dell XPS 13 9315',           1, 1499.00, 'Delivered',  '2024-05-22'),
(264, 17, 'LNVO-010', 'Lenovo Yoga 7 Gen 8',        2,  999.00, 'Processing', '2024-07-10'),
(265, 17, 'ASUS-004', 'ASUS ZenBook 14X OLED',      1, 1199.00, 'Delivered',  '2024-08-29'),
(266, 17, 'APPL-003', 'MacBook Air M2 15"',         1, 1299.00, 'Pending',    '2024-10-17'),
(267, 17, 'DELL-009', 'Dell XPS 15 9520',           1, 2199.00, 'Delivered',  '2024-12-05'),
(268, 17, 'MSI-002',  'MSI Prestige 14 Evo',        1,  999.00, 'Shipped',    '2025-01-23'),
(269, 17, 'HP-003',   'HP Pavilion x360 14"',       1,  849.00, 'Delivered',  '2024-04-11'),
(270, 17, 'LNVO-003', 'Lenovo IdeaPad Flex 5',      1,  849.00, 'Cancelled',  '2024-09-06'),
-- user 18 · Lưu Thị Rương · Cà Mau
(271, 18, 'DELL-012', 'Dell Alienware m15 R7',      1, 2499.00, 'Delivered',  '2024-01-17'),
(272, 18, 'MSI-006',  'MSI Titan GT77',             1, 3499.00, 'Shipped',    '2024-03-07'),
(273, 18, 'ASUS-009', 'ASUS ROG Zephyrus G16',      1, 1999.00, 'Delivered',  '2024-04-25'),
(274, 18, 'LNVO-009', 'Lenovo Legion 7 Gen 8',      1, 1999.00, 'Processing', '2024-06-13'),
(275, 18, 'HP-009',   'HP Omen 17 Gaming',          2, 1799.00, 'Delivered',  '2024-08-01'),
(276, 18, 'MSI-004',  'MSI Raider GE68HX',          1, 2499.00, 'Pending',    '2024-09-20'),
(277, 18, 'DELL-011', 'Dell G16 Gaming 7630',       1, 1499.00, 'Delivered',  '2024-11-08'),
(278, 18, 'ASUS-008', 'ASUS ROG Zephyrus G14',      1, 1499.00, 'Shipped',    '2024-12-26'),
(279, 18, 'LNVO-008', 'Lenovo Legion 5 Pro G8',     1, 1399.00, 'Delivered',  '2025-02-13'),
(280, 18, 'MSI-003',  'MSI Stealth 15M',            1,  999.00, 'Cancelled',  '2024-05-11'),
-- user 19 · Hà Văn Sơn · Vĩnh Long
(281, 19, 'DELL-003', 'Dell Vostro 3520',           1,  820.00, 'Delivered',  '2024-02-21'),
(282, 19, 'HP-004',   'HP ProBook 440 G10',         2,  950.00, 'Shipped',    '2024-04-10'),
(283, 19, 'LNVO-004', 'Lenovo ThinkPad E15 G4',     1,  899.00, 'Delivered',  '2024-05-29'),
(284, 19, 'ASUS-005', 'ASUS ExpertBook B1 B1502',   1,  799.00, 'Processing', '2024-07-17'),
(285, 19, 'DELL-004', 'Dell Vostro 5620',           1, 1050.00, 'Delivered',  '2024-09-05'),
(286, 19, 'MSI-001',  'MSI Modern 14 C12M',         1,  699.00, 'Pending',    '2024-10-24'),
(287, 19, 'HP-002',   'HP Pavilion 15-eg3086TU',    1,  749.00, 'Delivered',  '2024-12-12'),
(288, 19, 'LNVO-002', 'Lenovo IdeaPad Slim 5',      2,  699.00, 'Shipped',    '2025-01-30'),
(289, 19, 'DELL-001', 'Dell Inspiron 15 3511',      1,  699.00, 'Delivered',  '2024-03-31'),
(290, 19, 'ASUS-002', 'ASUS VivoBook 15X OLED',     1,  699.00, 'Cancelled',  '2024-08-20'),
-- user 20 · Kiều Thị Tuyết · Tây Ninh
(291, 20, 'APPL-004', 'MacBook Air M3 13"',         1, 1199.00, 'Delivered',  '2024-01-06'),
(292, 20, 'APPL-007', 'MacBook Pro M3 16"',         1, 2499.00, 'Shipped',    '2024-02-24'),
(293, 20, 'DELL-008', 'Dell XPS 13 Plus 9320',      1, 1799.00, 'Delivered',  '2024-04-14'),
(294, 20, 'HP-007',   'HP Spectre x360 16"',        1, 1999.00, 'Processing', '2024-06-02'),
(295, 20, 'LNVO-006', 'Lenovo ThinkPad X1 Carbon',  1, 1799.00, 'Delivered',  '2024-07-21'),
(296, 20, 'ASUS-006', 'ASUS ExpertBook B9 B9403',   1, 1699.00, 'Pending',    '2024-09-09'),
(297, 20, 'APPL-008', 'MacBook Pro M3 Max 16"',     1, 3499.00, 'Delivered',  '2024-10-28'),
(298, 20, 'DELL-009', 'Dell XPS 15 9520',           1, 2199.00, 'Shipped',    '2024-12-16'),
(299, 20, 'MSI-002',  'MSI Prestige 14 Evo',        2,  999.00, 'Delivered',  '2025-02-03'),
(300, 20, 'HP-006',   'HP Spectre x360 14"',        1, 1699.00, 'Cancelled',  '2024-05-05');

SELECT setval(pg_get_serial_sequence('orders','id'), 300);

-- ============================================================
--  SAMPLE QUERIES (PostgreSQL syntax)
-- ============================================================

-- 1. Tổng doanh thu
-- SELECT SUM(total_price) AS total_revenue FROM orders;

-- 2. Doanh thu theo thương hiệu
-- SELECT b.name AS brand, COUNT(o.id) AS total_orders, SUM(o.total_price) AS revenue
-- FROM orders o
-- JOIN products p ON o.sku = p.sku
-- JOIN brands b ON p.brand_id = b.id
-- GROUP BY b.name ORDER BY revenue DESC;

-- 3. Top 5 khách hàng chi tiêu nhiều nhất
-- SELECT u.full_name, u.city, COUNT(o.id) AS orders, SUM(o.total_price) AS total_spent
-- FROM orders o JOIN users u ON o.user_id = u.id
-- GROUP BY u.id, u.full_name, u.city
-- ORDER BY total_spent DESC LIMIT 5;

-- 4. Số đơn theo trạng thái
-- SELECT status, COUNT(*) AS count FROM orders GROUP BY status;

-- 5. Sản phẩm bán chạy nhất (top 10)
-- SELECT o.item_name, o.sku, COUNT(*) AS times_sold, SUM(o.total_price) AS revenue
-- FROM orders o GROUP BY o.sku, o.item_name ORDER BY times_sold DESC LIMIT 10;

-- 6. Đơn hàng của một user cụ thể
-- SELECT * FROM orders WHERE user_id = 2 ORDER BY order_date DESC;

-- 7. Doanh thu theo tháng
-- SELECT TO_CHAR(order_date, 'YYYY-MM') AS month, SUM(total_price) AS revenue
-- FROM orders GROUP BY month ORDER BY month;

-- 8. Thống kê khách hàng theo thành phố
-- SELECT u.city, COUNT(DISTINCT u.id) AS customers, SUM(o.total_price) AS revenue
-- FROM users u LEFT JOIN orders o ON u.id = o.user_id
-- GROUP BY u.city ORDER BY revenue DESC NULLS LAST;
